version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: new-web-lelang-api
    restart: always
    ports:
      - "8081:8080"
    env_file:
      - .env
    networks:
      - shared-network

networks:
  shared-network:
    external: true
