CREATE TABLE CMS.M_FAQ_CATEGORY (
    ID VARCHAR(36) PRIMARY KEY,
    NAMA_KATEGORI_ID VARCHAR(100) NOT NULL,
    NAMA_KATEGORI_EN VARCHAR(100) NOT NULL,
    ORDER_INDEX NUMERIC(5) NOT NULL
);

CREATE TABLE CMS.FAQS (
    ID VARCHAR(36) PRIMARY KEY,
    CATEGORY_ID VARCHAR(36) NOT NULL,
    QUESTION_ID VARCHAR(500) NOT NULL,
    QUESTION_EN VARCHAR(500) NOT NULL,
    ANSWER_ID TEXT NOT NULL,
    ANSWER_EN TEXT NOT NULL,
    ORDER_INDEX NUMERIC(5) NOT NULL,
    IS_ACTIVE NUMERIC(1) DEFAULT 1 NOT NULL,
    CONSTRAINT FK_FAQS_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CMS.M_FAQ_CATEGORY (ID)
);
