CREATE TABLE CMS.M_FAQ_CATEGORY (
    ID VARCHAR2(36) PRIMARY KEY,
    NAMA_KATEGORI_ID VARCHAR2(100) NOT NULL,
    NAMA_KATEGORI_EN VARCHAR2(100) NOT NULL,
    ORDER_INDEX NUMBER(5) NOT NULL
);

CREATE TABLE CMS.FAQS (
    ID VARCHAR2(36) PRIMARY KEY,
    CATEGORY_ID VARCHAR2(36) NOT NULL,
    QUESTION_ID VARCHAR2(500) NOT NULL,
    QUESTION_EN VARCHAR2(500) NOT NULL,
    ANSWER_ID CLOB NOT NULL,
    ANSWER_EN CLOB NOT NULL,
    ORDER_INDEX NUMBER(5) NOT NULL,
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT FK_FAQS_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CMS.M_FAQ_CATEGORY (ID)
);
