CREATE TABLE CMS.M_PROVINSI (
    ID VARCHAR2(36) PRIMARY KEY,
    NAMA_PROVINSI VARCHAR2(100)
);

CREATE TABLE CMS.M_KOTA (
    ID VARCHAR2(36) PRIMARY KEY,
    PROVINSI_ID VARCHAR2(36),
    NAMA_KOTA VARCHAR2(100),
    KODE_PREFIX VARCHAR2(5),
    CONSTRAINT FK_M_KOTA_PROVINSI FOREIGN KEY (PROVINSI_ID) REFERENCES CMS.M_PROVINSI (ID)
);

CREATE TABLE CMS.M_KATEGORI (
    ID VARCHAR2(36) PRIMARY KEY,
    NAMA_KATEGORI VARCHAR2(100)
);

CREATE TABLE CMS.M_TIPE_ASET (
    ID VARCHAR2(36) PRIMARY KEY,
    KATEGORI_ID VARCHAR2(36),
    NAMA_TIPE VARCHAR2(100),
    CONSTRAINT FK_M_TIPE_ASET_KATEGORI FOREIGN KEY (KATEGORI_ID) REFERENCES CMS.M_KATEGORI (ID)
);

CREATE TABLE CMS.M_METODE_PENJUALAN (
    ID VARCHAR2(36) PRIMARY KEY,
    NAMA_METODE VARCHAR2(50)
);

CREATE TABLE CMS.M_KPKNL (
    ID VARCHAR2(36) PRIMARY KEY,
    KODE_KPKNL VARCHAR2(50),
    KANTOR_WILAYAH VARCHAR2(100),
    NAMA_KANTOR VARCHAR2(255),
    ALAMAT VARCHAR2(500),
    NOMOR_TELEPON VARCHAR2(50)
);
