CREATE TABLE CMS.M_PROVINSI (
    ID VARCHAR(36) PRIMARY KEY,
    NAMA_PROVINSI VARCHAR(100)
);

CREATE TABLE CMS.M_KOTA (
    ID VARCHAR(36) PRIMARY KEY,
    PROVINSI_ID VARCHAR(36),
    NAMA_KOTA VARCHAR(100),
    KODE_PREFIX VARCHAR(5),
    CONSTRAINT FK_M_KOTA_PROVINSI FOREIGN KEY (PROVINSI_ID) REFERENCES CMS.M_PROVINSI (ID)
);

CREATE TABLE CMS.M_KATEGORI (
    ID VARCHAR(36) PRIMARY KEY,
    NAMA_KATEGORI VARCHAR(100)
);

CREATE TABLE CMS.M_TIPE_ASET (
    ID VARCHAR(36) PRIMARY KEY,
    KATEGORI_ID VARCHAR(36),
    NAMA_TIPE VARCHAR(100),
    CONSTRAINT FK_M_TIPE_ASET_KATEGORI FOREIGN KEY (KATEGORI_ID) REFERENCES CMS.M_KATEGORI (ID)
);

CREATE TABLE CMS.M_METODE_PENJUALAN (
    ID VARCHAR(36) PRIMARY KEY,
    NAMA_METODE VARCHAR(50)
);

CREATE TABLE CMS.M_KPKNL (
    ID VARCHAR(36) PRIMARY KEY,
    KODE_KPKNL VARCHAR(50),
    KANTOR_WILAYAH VARCHAR(100),
    NAMA_KANTOR VARCHAR(255),
    ALAMAT VARCHAR(500),
    NOMOR_TELEPON VARCHAR(50)
);
