CREATE TABLE CMS.BANNER_SLIDER_PROMOSI (
    ID VARCHAR(36) PRIMARY KEY,
    IMAGE_URL VARCHAR(500) NOT NULL,
    TARGET_URL VARCHAR(500),
    ORDER_INDEX NUMERIC(5) NOT NULL,
    IS_ACTIVE NUMERIC(1) DEFAULT 1
);

