CREATE TABLE CMS.BANNER_SLIDER_PROMOSI (
    ID VARCHAR2(36) PRIMARY KEY,
    IMAGE_URL VARCHAR2(500) NOT NULL,
    TARGET_URL VARCHAR2(500),
    ORDER_INDEX NUMBER(5) NOT NULL,
    IS_ACTIVE NUMBER(1) DEFAULT 1
);

