CREATE TABLE CMS.USERS (
    ID VARCHAR2(36) PRIMARY KEY,
    USERNAME VARCHAR2(50) NOT NULL,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    ROLE VARCHAR2(20) DEFAULT 'ADMIN' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSDATE NOT NULL,
    CONSTRAINT UK_USERS_USERNAME UNIQUE (USERNAME)
);

CREATE TABLE CMS.M_KATALOG (
    ID VARCHAR2(36) PRIMARY KEY,
    FILE_NAME VARCHAR2(255) NOT NULL,
    FILE_URL VARCHAR2(500) NOT NULL,
    FILE_SIZE NUMBER NOT NULL,
    STATUS VARCHAR2(50) NOT NULL,
    UPLOADED_BY VARCHAR2(36),
    CREATED_AT TIMESTAMP DEFAULT SYSDATE NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT SYSDATE NOT NULL,
    CONSTRAINT CK_M_KATALOG_STATUS CHECK (STATUS IN ('PUBLISHED', 'ARCHIVED')),
    CONSTRAINT FK_M_KATALOG_UPLOADED_BY FOREIGN KEY (UPLOADED_BY) REFERENCES CMS.USERS (ID)
);
