CREATE TABLE CMS.USERS (
    ID VARCHAR(36) PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    ROLE VARCHAR(20) DEFAULT 'ADMIN' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_USERS_USERNAME UNIQUE (USERNAME)
);

CREATE TABLE CMS.M_KATALOG (
    ID VARCHAR(36) PRIMARY KEY,
    FILE_NAME VARCHAR(255) NOT NULL,
    FILE_URL VARCHAR(500) NOT NULL,
    FILE_SIZE NUMERIC NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    UPLOADED_BY VARCHAR(36),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT CK_M_KATALOG_STATUS CHECK (STATUS IN ('PUBLISHED', 'ARCHIVED')),
    CONSTRAINT FK_M_KATALOG_UPLOADED_BY FOREIGN KEY (UPLOADED_BY) REFERENCES CMS.USERS (ID)
);
