CREATE TABLE CMS.M_PIC (
    ID VARCHAR(36) PRIMARY KEY,
    NAMA VARCHAR(255) NOT NULL,
    NO_HP VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100),
    KANTOR_CABANG VARCHAR(255)
);

CREATE TABLE CMS.ASSET_CONTACTS (
    ASSET_ID VARCHAR(36) NOT NULL,
    PIC_ID VARCHAR(36) NOT NULL,
    URUTAN NUMERIC(2),
    CONSTRAINT PK_ASSET_CONTACTS PRIMARY KEY (ASSET_ID, PIC_ID),
    CONSTRAINT FK_ASSET_CONTACTS_ASSET FOREIGN KEY (ASSET_ID) REFERENCES CMS.ASSETS (ID),
    CONSTRAINT FK_ASSET_CONTACTS_PIC FOREIGN KEY (PIC_ID) REFERENCES CMS.M_PIC (ID)
);
