CREATE TABLE CMS.M_PIC (
    ID VARCHAR2(36) PRIMARY KEY,
    NAMA VARCHAR2(255) NOT NULL,
    NO_HP VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(100),
    KANTOR_CABANG VARCHAR2(255)
);

CREATE TABLE CMS.ASSET_CONTACTS (
    ASSET_ID VARCHAR2(36) NOT NULL,
    PIC_ID VARCHAR2(36) NOT NULL,
    URUTAN NUMBER(2),
    CONSTRAINT PK_ASSET_CONTACTS PRIMARY KEY (ASSET_ID, PIC_ID),
    CONSTRAINT FK_ASSET_CONTACTS_ASSET FOREIGN KEY (ASSET_ID) REFERENCES CMS.ASSETS (ID),
    CONSTRAINT FK_ASSET_CONTACTS_PIC FOREIGN KEY (PIC_ID) REFERENCES CMS.M_PIC (ID)
);
