CREATE TABLE CMS.MONTHLY_CATALOGS (
    ID VARCHAR2(36) PRIMARY KEY,
    TITLE VARCHAR2(255) NOT NULL,
    MONTH VARCHAR2(20) NOT NULL,
    YEAR VARCHAR2(4) NOT NULL,
    MINIO_PATH VARCHAR2(500) NOT NULL,
    UPLOADED_BY VARCHAR2(36),
    CREATED_AT TIMESTAMP DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_MONTHLY_CATALOGS_UPLOADED_BY FOREIGN KEY (UPLOADED_BY) REFERENCES CMS.USERS (ID)
);
