CREATE TABLE CMS.MONTHLY_CATALOGS (
    ID VARCHAR(36) PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    MONTH VARCHAR(20) NOT NULL,
    YEAR VARCHAR(4) NOT NULL,
    MINIO_PATH VARCHAR(500) NOT NULL,
    UPLOADED_BY VARCHAR(36),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_MONTHLY_CATALOGS_UPLOADED_BY FOREIGN KEY (UPLOADED_BY) REFERENCES CMS.USERS (ID)
);
